"""
Telangana Lok Sabha ↔ Assembly constituency seed data (official-style grouping).

Single source for populate scripts and admin /populate-data.
Assembly constituency_number values follow Telangana EC numbering (1–119).
Parliamentary constituency_number is fixed 1–17 per state delimitation.

Note: Row 6 (Medak Lok Sabha) remains as a parliamentary seat with no assemblies in this
district-wise grouping (all seats listed under Zaheerabad (SC) use parliament_constituency_id=5).
"""

MANUAL_CONSTITUENCIES = [
    {"number": 1, "name": "Adilabad (ST)"},
    {"number": 2, "name": "Peddapalle (SC)"},
    {"number": 3, "name": "Karimnagar"},
    {"number": 4, "name": "Nizamabad"},
    {"number": 5, "name": "Zaheerabad (SC)"},
    {"number": 6, "name": "Medak"},
    {"number": 7, "name": "Malkajgiri"},
    {"number": 8, "name": "Secunderabad"},
    {"number": 9, "name": "Hyderabad"},
    {"number": 10, "name": "Chevella"},
    {"number": 11, "name": "Mahbubnagar"},
    {"number": 12, "name": "Nagarkurnool (SC)"},
    {"number": 13, "name": "Nalgonda"},
    {"number": 14, "name": "Bhuvangiri"},
    {"number": 15, "name": "Warangal (SC)"},
    {"number": 16, "name": "Mahaboobabad (ST)"},
    {"number": 17, "name": "Khammam"},
]

# Maps parliamentary constituency_number -> list of assembly constituencies
ASSEMBLY_CONSTITUENCIES = {
    1: [  # Adilabad (ST)
        {"number": 5, "name": "Asifabad(ST)"},
        {"number": 6, "name": "Khanapur(ST)"},
        {"number": 7, "name": "Adilabad"},
        {"number": 8, "name": "Boath(ST)"},
        {"number": 9, "name": "Nirmal"},
        {"number": 10, "name": "Mudhole"},
        {"number": 1, "name": "Sirpur"},
        {"number": 2, "name": "Chennur(SC)"},
        {"number": 3, "name": "Bellampalli(SC)"},
        {"number": 4, "name": "Mancherial"},
    ],
    2: [  # Peddapalle (SC)
        {"number": 22, "name": "Dharmapuri(SC)"},
        {"number": 23, "name": "Ramagundam"},
        {"number": 24, "name": "Manthani"},
        {"number": 25, "name": "Peddapalle"},
    ],
    3: [  # Karimnagar
        {"number": 26, "name": "Karimnagar"},
        {"number": 27, "name": "Choppadandi(SC)"},
        {"number": 28, "name": "Vemulawada"},
        {"number": 29, "name": "Sircilla"},
        {"number": 30, "name": "Manakondur(SC)"},
        {"number": 31, "name": "Huzurabad"},
        {"number": 32, "name": "Husnabad"},
    ],
    4: [  # Nizamabad
        {"number": 11, "name": "Armur"},
        {"number": 12, "name": "Bodhan"},
        {"number": 13, "name": "Jukkal(SC)"},
        {"number": 14, "name": "Banswada"},
        {"number": 15, "name": "Yellareddy"},
        {"number": 16, "name": "Kamareddy"},
        {"number": 17, "name": "Nizamabad Urban"},
        {"number": 18, "name": "Nizamabad Rural"},
        {"number": 19, "name": "Balkonda"},
        {"number": 20, "name": "Koratla"},
        {"number": 21, "name": "Jagtial"},
    ],
    5: [  # Zaheerabad (SC) — district-wise grouping incl. former Medak LS segment seats
        {"number": 35, "name": "Narayankhed"},
        {"number": 36, "name": "Andole(SC)"},
        {"number": 37, "name": "Narsapur"},
        {"number": 38, "name": "Zaheerabad(SC)"},
        {"number": 39, "name": "Sangareddy"},
        {"number": 40, "name": "Patancheru"},
        {"number": 41, "name": "Dubbak"},
        {"number": 42, "name": "Gajwel"},
        {"number": 33, "name": "Siddipet"},
        {"number": 34, "name": "Medak"},
    ],
    6: [],  # Medak (parliamentary seat retained; no assemblies under this grouping)
    7: [  # Malkajgiri
        {"number": 43, "name": "Medchal"},
        {"number": 44, "name": "Malkajgiri"},
        {"number": 45, "name": "Quthbullapur"},
        {"number": 46, "name": "Kukatpally"},
        {"number": 47, "name": "Uppal"},
        {"number": 49, "name": "Lal Bahadur Nagar"},
    ],
    8: [  # Secunderabad
        {"number": 71, "name": "Secunderabad Cantt(SC)"},
        {"number": 57, "name": "Musheerabad"},
        {"number": 70, "name": "Secunderabad"},
    ],
    9: [  # Hyderabad
        {"number": 59, "name": "Amberpet"},
        {"number": 60, "name": "Khairatabad"},
        {"number": 61, "name": "Jubilee Hills"},
        {"number": 62, "name": "Sanathnagar"},
        {"number": 63, "name": "Nampally"},
        {"number": 64, "name": "Karwan"},
        {"number": 65, "name": "Goshamahal"},
        {"number": 66, "name": "Charminar"},
        {"number": 67, "name": "Chandrayangutta"},
        {"number": 68, "name": "Yakutpura"},
        {"number": 69, "name": "Bahadurpura"},
        {"number": 58, "name": "Malakpet"},
    ],
    10: [  # Chevella
        {"number": 50, "name": "Maheswaram"},
        {"number": 51, "name": "Rajendranagar"},
        {"number": 52, "name": "Serilingampally"},
        {"number": 53, "name": "Chevella(SC)"},
        {"number": 54, "name": "Pargi"},
        {"number": 55, "name": "Vicarabad(SC)"},
        {"number": 56, "name": "Tandur"},
        {"number": 84, "name": "Shadnagar"},
    ],
    11: [  # Mahbubnagar
        {"number": 72, "name": "Kodangal"},
        {"number": 73, "name": "Narayanpet"},
        {"number": 74, "name": "Mahbubnagar"},
        {"number": 75, "name": "Jadcherla"},
        {"number": 76, "name": "Devarkadra"},
        {"number": 77, "name": "Makthal"},
        {"number": 78, "name": "Wanaparthy"},
        {"number": 79, "name": "Gadwal"},
        {"number": 80, "name": "Alampur(SC)"},
    ],
    12: [  # Nagarkurnool (SC)
        {"number": 81, "name": "Nagarkurnool"},
        {"number": 82, "name": "Achampet(SC)"},
        {"number": 83, "name": "Kalwakurthy"},
        {"number": 85, "name": "Kollapur"},
    ],
    13: [  # Nalgonda
        {"number": 86, "name": "Devarakonda(ST)"},
        {"number": 87, "name": "Nagarjuna Sagar"},
        {"number": 88, "name": "Miryalaguda"},
        {"number": 89, "name": "Huzurnagar"},
        {"number": 90, "name": "Kodad"},
        {"number": 91, "name": "Suryapet"},
        {"number": 92, "name": "Nalgonda"},
    ],
    14: [  # Bhuvangiri
        {"number": 93, "name": "Munugode"},
        {"number": 94, "name": "Bhongir"},
        {"number": 95, "name": "Nakrekal(SC)"},
        {"number": 96, "name": "Thungathurthi(SC)"},
        {"number": 97, "name": "Alair"},
        {"number": 48, "name": "Ibrahimpatnam"},
    ],
    15: [  # Warangal (SC)
        {"number": 98, "name": "Jangaon"},
        {"number": 99, "name": "Ghanpur (Station)(SC)"},
        {"number": 100, "name": "Palakurthi"},
        {"number": 104, "name": "Parkal"},
        {"number": 105, "name": "Warangal West"},
        {"number": 106, "name": "Warangal East"},
        {"number": 107, "name": "Waradhanapet(SC)"},
    ],
    16: [  # Mahaboobabad (ST)
        {"number": 108, "name": "Bhupalpalle"},
        {"number": 109, "name": "Mulugu(ST)"},
        {"number": 110, "name": "Pinapaka(ST)"},
        {"number": 111, "name": "Yellandu(ST)"},
        {"number": 119, "name": "Bhadrachalam(ST)"},
        {"number": 101, "name": "Dornakal(ST)"},
        {"number": 102, "name": "Mahabubabad(ST)"},
        {"number": 103, "name": "Narsampet"},
    ],
    17: [  # Khammam
        {"number": 112, "name": "Khammam"},
        {"number": 113, "name": "Palair"},
        {"number": 114, "name": "Madhira(SC)"},
        {"number": 115, "name": "Wyra(ST)"},
        {"number": 116, "name": "Sathupalle(SC)"},
        {"number": 117, "name": "Kothagudem"},
        {"number": 118, "name": "Aswaraopeta(ST)"},
    ],
}
